package shoppingList.Command;

/**
 * Represents the outcome of a command execution.
 * Encapsulates the response message to be displayed to the user and
 * a flag indicating whether the application's main loop should continue.
 */
public class CommandResult {

    private final boolean keepRunning;
    private final String response;

    /**
     * Constructs a result with the specified state and feedback message.
     *
     * @param keepRunning Set to true to continue the application loop, false to exit.
     * @param toPrint     The message string to be displayed in the CLI.
     */
    public CommandResult(boolean keepRunning, String toPrint) {
        this.keepRunning = keepRunning;
        this.response = toPrint;
    }

    /**
     * Retrieves the status of the application loop.
     *
     * @return true if the application should keep running.
     */
    public boolean getKeepRunning() {
        return keepRunning;
    }

    /**
     * Retrieves the feedback message generated by the command.
     *
     * @return The response string.
     */
    public String getResponse() {
        return response;
    }
}